[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"
keyfile = "apikey.crypt"
tries = 5
user_agent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36"

[asdf-vm]
source = "git"
git = "https://github.com/asdf-vm/asdf"
prefix = "v"

[auth]
source = "git"
git = "https://github.com/xsy420/auth"
prefix = "v"

[battery-monitor]
source = "git"
git = "https://github.com/xsy420/battery-monitor"
prefix = "v"

[bilibili]
source = "git"
git = "https://github.com/msojocs/bilibili-linux"
prefix = "v"

[blockbench]
source = "git"
git = "https://github.com/JannisX11/blockbench"
prefix = "v"

[baidunetdisk-bin]
source = "aur"

[cherry-studio-bin]
source = "git"
git = "https://github.com/cherryHQ/cherry-studio"
prefix = "v"

[dmg2img]
source = "aur"

[downgrade]
source = "git"
git = "https://github.com/archlinux-downgrade/downgrade"
prefix = "v"

[euporie]
source = "git"
git = "https://github.com/joouha/euporie"
prefix = "v"

[fzf-make]
source = "git"
git = "https://github.com/kyu08/fzf-make"
prefix = "v"

[google-chrome]
source = "apt"
mirror = "https://dl.google.com/linux/chrome/deb/"
pkg = "google-chrome-stable"
suite = "stable"
repo = "main"
strip_release = true

[greenclip]
source = "hackage"

[harlequin]
source = "git"
git = "https://github.com/tconbeer/harlequin"
prefix = "v"

[harlequin-mysql]
source = "git"
git = "https://github.com/tconbeer/harlequin-mysql"
prefix = "v"

[haskell-semigroups]
source = "hackage"
hackage = "semigroups"

[haskell-wordexp]
source = "hackage"
hackage = "wordexp"

[lazydocker]
source = "git"
git = "https://github.com/jesseduffield/lazydocker"
prefix = "v"

[libcyaml]
source = "git"
git = "https://github.com/tlsa/libcyaml"
prefix = "v"

[libxls]
source = "git"
git = "https://github.com/libxls/libxls"
prefix = "v"

[linuxqq-nt-bwrap]
source = "regex"
url = "https://cdn-go.cn/qq-web/im.qq.com_new/latest/rainbow/linuxConfig.js"
regex = "QQ_(.*)_amd64_01.deb"

[mysql]
source = "regex"
url = "https://dev.mysql.com/downloads/mysql/"
regex = "MySQL Community Server ([0-9\\.]+) "
user_agent = "curl/8.19.0"

[navicat17-premium-cs]
source = "regex"
url = "https://www.navicat.com/products/navicat-premium-release-note#L"
regex = "Navicat Premium \\(Linux\\) version (.*)</b>"

[pacfiles]
source = "git"
git = "https://github.com/lilydjwg/pacfiles"
prefix = "v"

[python-aenum]
source = "git"
git = "https://github.com/ethanfurman/aenum"
prefix = "v"

['python-backports.cached_property']
source = "git"
git = "https://github.com/penguinolog/backports.cached_property"

[python-chafapy]
source = "git"
git = "https://github.com/guardkenzie/chafa.py"
prefix = "v"

[python-code-minimap]
source = "git"
git = "https://github.com/joouha/python-code-minimap"
prefix = "v"

[python-flatlatex]
source = "git"
git = "https://github.com/jb-leger/flatlatex"
prefix = "v"

[python-imageio-ffmpeg]
source = "git"
git = "https://github.com/imageio/imageio-ffmpeg"
prefix = "v"

[python-img2unicode]
source = "git"
git = "https://github.com/matrach/img2unicode"
use_commit = true

[python-jupytext]
source = "git"
git = "https://github.com/mwouts/jupytext"
prefix = "v"

[python-moviepy]
source = "git"
git = "https://github.com/Zulko/moviepy"
prefix = "v"

[python-mtable]
source = "git"
git = "https://github.com/liuyug/mtable"
use_commit = true

[python-pandas-stubs]
source = "git"
git = "https://github.com/pandas-dev/pandas-stubs"
prefix = "v"

[python-pathlib-abc]
source = "git"
git = "https://github.com/barneygale/pathlib-abc"

[python-proglog]
source = "git"
git = "https://github.com/Edinburgh-Genome-Foundry/Proglog"
prefix = "v"

[python-questionary]
source = "git"
git = "https://github.com/tmbo/questionary"
prefix = "v"

[python-shandy-sqlfmt]
source = "pypi"
pypi = "shandy-sqlfmt"

[python-sixelcrop]
source = "pypi"
pypi = "sixelcrop"

[python-teimpy]
source = "git"
git = "https://github.com/ar90n/teimpy"
prefix = "v"

[python-textual-fastdatatable]
source = "git"
git = "https://github.com/tconbeer/textual-fastdatatable"
prefix = "v"

[python-textual-textarea]
source = "pypi"
pypi = "textual-textarea"

[python-timg]
source = "pypi"
pypi = "timg"

[python-universal_pathlib]
source = "git"
git = "https://github.com/fsspec/universal_pathlib"
prefix = "v"

[reg]
source = "git"
git = "https://github.com/genuinetools/reg"
prefix = "v"

[ruby-fusuma]
source = "gems"
gems = "fusuma"

[td-tui]
source = "git"
git = "https://github.com/voioo/td"
prefix = "v"

[typora]
source = "regex"
url = "https://www.typora.io/releases/stable.html"
regex = "typora_([0-9\\.]+)_amd64.deb"

[xwin]
source = "cratesio"

[yay]
source = "github"
github = "Jguer/yay"
use_latest_release = true
prefix = "v"
