[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"
keyfile = "apikey.crypt"

[auth]
source = "github"
github = "nnyyxxxx/auth"
use_latest_release = true
prefix = "v"

[battery-monitor]
source = "github"
github = "xsy420/battery-monitor"
use_latest_release = true
prefix = "v"
