name: nvchecker
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  nvchecker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Unlock secrets
        run: sudo apt-get update && sudo apt-get install git-crypt -y && echo ${{ secrets.GIT_CRYPT_KEY }} | base64 -d | git-crypt unlock -
      - name: editorconfig-checker
        run: sudo npm install --global --save-dev editorconfig-checker && sudo editorconfig-checker
      - name: Remove proxy in nvchecker.toml when running GitHub Action
        run: sed -i '/^proxy/d' nvchecker.toml
      - name: nvchecker
        run: sudo pip install nvchecker --break-system-packages && time nvchecker -c nvchecker.toml
